version: '3.8'

services:
  web:
    image: 'web'
    build:
      context: .
    container_name: web
    depends_on:
      - app
    ports:
      - "9091:5173"

  app:
    image: 'app'
    build:
      context: .
    container_name: app
    depends_on:
      - db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/demo
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - "9090:8089"

  db:
    image: 'postgres'
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=demo
    ports:
      - "1010:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

networks:
  default:
    name: demo
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 8530